name = "Bootstrap Freelancer"
license = "MIT"
licenselink = "https://github.com/joe-mccarthy/bootstrap-freelancer/blob/main/LICENSE"
description = "Theme based on the Bootstrap Freelancer Template"

homepage = "https://github.com/joe-mccarthy/bootstrap-freelancer"

demosite = "https://joe-mccarthy.github.io/bootstrap-freelancer"

tags = ["blog", "company", "Personal"]
features = ["bootstrap", "projects", "blog"]

[author]
    name = "Joe mcCarthy"
    homepage = "https://joe-mccarthy.github.io/"